export const app_text = {
    name: "Restaurant Name",
    description: "Customisable website for restaurants",
    author: "Restaurant Company",
    url:  "https://restaurant-website-tinker-devs.vercel.app/",
    tagline: "Delicious meals, Anytime",
    type: 'Restaurant',
    footerCopyright: `© 2025 Restaurnat Name. All rights reserved.`,
    full_address: "67 Adebowale Street, Magodo, Lagos State ",
    street_address: "67 Adebowale Street, Magodo",
    addressLocality: "Lagos",
    postalCode: "101241",
    country: "Nigeria",
    phone: "+234 0908765432",
    email: 'customisablerestaurantwebsite@restaurant.com',
    globalKeywords: ["Restaurant, Fine Dining, Reservations, Menu, Delicious, Tasty Meals, Appetisers, Main course, Deserts, Drinks"],
    creator: 'Tinker Devs',
    cuisine: 'Nigerian, Continental',
    priceRange: '₦5,000.00 - ₦50,0000.00'
}