import styles from './home.module.css';


export default function HomeTemplate() {
  return (
    <div
    className={styles.container}
    >
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>
      <h1>Home Page</h1>

    {/* <h1

    >
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>

    </h1>
    <h1
    >
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>

    </h1>
    <h1
    >
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>

    </h1>
    <h1
    >
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>
      <p>Home Page</p>

    </h1> */}
    </div>

  );
}
